kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: jgibson02/bloombus-client
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
      branch:
        - master

  - name: deploy
    image: jgibson02/bloombus-client
    detach: true
    when:
      event:
        - push
      branch:
        - master

  - name: discord
    image: appleboy/drone-discord
    secrets: [discord_webhook_id, discord_webhook_token]
    when:
      event:
        - push
      branch:
        - master
      status: [success, failure]
