kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: jgibson02/bloombus-client
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master

  - name: deploy
    image: docker
    commands:
      - docker -v
      - docker run --rm jgibson02/bloombus-client
      - docker rmi jgibson02/bloombus-client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker:/root/.docker
    privileged: true
    when:
      event:
        - push
      branch:
        - master

  - name: discord
    image: appleboy/drone-discord
    secrets: [discord_webhook_id, discord_webhook_token]
    when:
      branch:
        - master
      status: [success, failure]
