kind: pipeline
name: client

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: jgibson02/bloombus-client
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
      branch:
        - master

  - name: deploy
    image: docker
    commands:
      - docker pull jgibson02/bloombus-client
      - docker stop client
      - docker run -d --name client jgibson02/bloombus-client
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      event:
        - push
      branch:
        - master

  - name: discord
    image: appleboy/drone-discord
    secrets: [discord_webhook_id, discord_webhook_token]
    message: |
      {{ #success build.status }}
        build {{ build.number }} succeeded. Good job.
      {{ else }}
        build {{ build.number }} failed. Fix me please.
      {{ /success }}

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
